### ISSUE TITLE
bug: Error in parsing commitmsg with dirty submodule

### ISSUE THREAD

**Issue by thatlittleboy** [gbprod/tree-sitter-gitcommit#10]
## Description

The current parser doesn't support dirty submodules. It errors out. See example below.

## Steps to Reproduce

1. Run the following command to generate a test file
```bash
$ cat << EOF > a.COMMIT_EDITMSG
feat(vim): some title text

This commit_editmsg comes from a real life example, in a repository containing a
dirty submodule.
#
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
# Your branch is ahead of 'origin/master' by 8 commits.
#   (use "git push" to publish your local commits)
#
# Changes to be committed:
#	modified:   ../../../.config/nvim/after/ftplugin/markdown.vim
#
# Changes not staged for commit:
#	modified:   ../../../.config/nvim/lua/xkcd/plugins/nvim-tree.lua
#	modified:   ../../../.config/setup-scripts-submodule (modified content)

# vim: ft=gitcommit:noexpandtab
EOF
```
The offending line is the final `modified` line, above the vim modeline.

2. Then `tree-sitter parse a.COMMIT_EDITMSG` to run the query or via neovim treesitter Playground, you can see the errors highlighted in red.
    <img src="https://user-images.githubusercontent.com/30731072/210161412-1eddd813-62ce-4a28-aa9e-613dd500b771.png" width="500">

## Expected output

No error when parsing.

**Comment by gbprod** [comment]
Good catch, I try to fix it soon !

**Comment by gbprod** [comment]
Fixed

**Comment by przepompownia** [comment]
Thanks. I'll check it after merging into nvim-treesitter.

**Comment by przepompownia** [comment]
Works!
