### ISSUE TITLE
`(untracked content)` of submodule causes error

### ISSUE THREAD

**Issue by przepompownia** [gbprod/tree-sitter-gitcommit#19]
```gitcommit

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
# Your branch is up to date with 'origin/master'.
#
# Changes to be committed:
#       modified:   .my.cnf
#
# Changes not staged for commit:
#       modified:   .bar (untracked content)
#       modified:   .baz
#
# Untracked files:
        .foo
```

![image](https://user-images.githubusercontent.com/11404453/210354074-c7928d34-1eb4-4889-88f1-d0a27655010a.png)
btw, thanks for nord colosrcheme :)

**Comment by gbprod** [comment]
Hey!

It seems that it's the same as #10, I'm working on a fix.

Thanks for reporting reporting this issue!

Glad you enjoy my theme 🙂

**Comment by przepompownia** [comment]
Indeed, there is a similar issue so it can be closed. 

Many years I did not found any dark theme acceptable for my eyes so I worked only on light. I also found equivalents for  tmux and kitty afterwards.

**Comment by gbprod** [comment]
Have a look to the official website, there are a lot of ports : https://www.nordtheme.com/ports
