### ISSUE TITLE
Summary overflow and 2nd line aren't highlighted

### ISSUE THREAD

**Issue by pghk** [gbprod/tree-sitter-gitcommit#23]
Hi, thank you for making this! I'm new to Nvim and Treesitter, so apologies if I'm off-base or missing something.

It looks like this parser applies the highlight groups @text and @error to the overflow and second line, respectively. These [aren't linked to any standard groups](https://neovim.io/doc/user/treesitter.html#treesitter-highlight) by default, thus requiring us to configure them explicitly:

```lua
vim.api.nvim_set_hl(0, '@text', { link = 'Normal' })
vim.api.nvim_set_hl(0, '@error', { link = 'Error' })
```

For what it's worth, the 3rd line behaves as expected, appearing as normal not-highlighted text. It's only on the 1st line where the overflow text seems to continue using the hl linked to @text.title:

Expected behavior:
<img width="815" alt="Screenshot 2023-01-16 at 4 50 35 PM" src="https://user-images.githubusercontent.com/24971239/212770832-873bd91d-837e-4abf-b3f5-833fe1234be5.png">

Actual behavior:
<img width="814" alt="Screenshot 2023-01-16 at 4 49 13 PM" src="https://user-images.githubusercontent.com/24971239/212770853-17ad5cda-e4b8-4c17-8bcf-b001130644d3.png">

**Comment by gbprod** [comment]
Hi @pghk !
Thanks for your  feedback.
Since nvim 0.8, `@error` and `@text` are te standard highlight groups, I think your colorscheme does not define those groups. What's your colorsheme ?

Using a treesitter compliant colorscheme, I have no problems : 
![2023-01-17-091502_747x106_scrot](https://user-images.githubusercontent.com/3751019/212844502-8823680a-9363-4ade-a74b-4ceabb75ff01.png)

**Comment by pghk** [comment]
Ah! My mistake, sorry. I didn't expect colorschemes to be _defining_ groups, I assumed they'd only override existing ones.

I'm using [kaicataldo/material.vim](https://github.com/kaicataldo/material.vim), which I can see now [does define a lot of treesitter groups](https://github.com/kaicataldo/material.vim/blob/main/colors/material.vim#L563), just not these two.

Thanks!
