### ISSUE TITLE
Commit types don't count towards summary limit

### ISSUE THREAD

**Issue by pghk** [gbprod/tree-sitter-gitcommit#24]
Given a theme setting of ` vim.api.nvim_set_hl(0, '@text', { link = 'Normal' })`, and a commit summary longer than 50 characters, I'd expect all characters past column 50 to appear as normal text:

<img width="820" alt="Screenshot 2023-01-16 at 5 00 08 PM" src="https://user-images.githubusercontent.com/24971239/212772481-426732cd-0ab0-4f45-8846-3ab34648ea3e.png">

However, when the prefix section is recognized as a [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) _type_ element, this is no longer the case:
<img width="809" alt="Screenshot 2023-01-16 at 5 02 27 PM" src="https://user-images.githubusercontent.com/24971239/212772625-0e1ca518-9ba9-408d-ac17-33d34bda0cae.png">

**Comment by gbprod** [comment]
Yes, I'm aware of this issue...
I will try to fix it soon

**Comment by gbprod** [comment]
Fixed by #25
