### ISSUE TITLE
Customizable line limit

### ISSUE THREAD

**Issue by wcampbell0x2a** [gbprod/tree-sitter-gitcommit#26]
I use 70 instead of 50 for my line limit. Is there a way to customize this with this plugin?

**Comment by gbprod** [comment]
This parser does not allows to customize line length limit. This value comes from the official git documentation (https://git-scm.com/docs/git-commit#_discussion) and from the old vim syntax highlighting.

If you're using nvim-treesitter, I'm quite you can adapt your highlighting with custom queries.
