### ISSUE TITLE
Highlight syntax work isn't correct for squash

### ISSUE THREAD

**Issue by judaew** [gbprod/tree-sitter-gitcommit#27]
Steps to reproduce:

```sh
touch test1 test2
git commit test1 -m "ci: perf"
git commit test2 -m "[wip] ci: fix #997"
git rebase -i @~2

# Squash the second commit to the first
```

Actual Result (see image):
<img width="773" alt="Screenshot 2023-03-10 at 15 31 35" src="https://user-images.githubusercontent.com/41125715/224330967-56abf08c-5c4f-419f-a3bd-fe7e10c8ad17.png">

**Comment by gbprod** [comment]
Thanks for reporting this.

Can you explain what seems incorrect to you ?

Thanks

**Comment by judaew** [comment]
Sorry, everything looks correct. I mistakenly thought that the lines "This is the 1st commit message:" shouldn't be highlighted.
