### ISSUE TITLE
documentation request: CONTRIBUTING.md

### ISSUE THREAD

**Issue by SKalt** [gbprod/tree-sitter-gitcommit#28]
Hi, are you open to contributions for this repo? If so, are there standards I should follow (apart from `./CODE_OF_CONDUCT.md`)? For example,
- should I keep my commit messages conventional?
- I should check in the generated  `src` code if I modified `grammar.js`, right?

**Comment by gbprod** [comment]
Hi!
Sure I'm open to contribution :)
Maybe I should write a `CONTRIBUTING.md` documentation :sweat_smile: 


> should I keep my commit messages conventional?

Yes, I prefer

> I should check in the generated `src` code if I modified `grammar.js`, right?

If you update  `grammar.js`, you must run `npm run build` to update parser. If you don't, CI will remind it to you.

**Comment by gbprod** [comment]
I've introduced a `CONTRIBUTING.md` documentation https://github.com/gbprod/tree-sitter-gitcommit/commit/17235998809be904892f14ee57730d96795e9323 

Thanks for your feedback
