### ISSUE TITLE
Documentation request: add usage instructions to the README

### ISSUE THREAD

**Issue by SKalt** [gbprod/tree-sitter-gitcommit#29]
I'd like to install `tree-sitter-gitcommit` to use with an editor or as part of a parsing project. Having instructions in the `./README.md` would help users like me get started.

**Comment by gbprod** [comment]
Hi!
I'm not sure thant here is the place we should add instruction about usage as it depends on the library you will use with it, maybe [tree-sitter](https://tree-sitter.github.io/tree-sitter/using-parsers) website or library repos like [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) or [rust-sitter](https://github.com/hydro-project/rust-sitter) or [binding_web](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web]... will be more apropriated.
