### ISSUE TITLE
feature request: publish to npm and crates.io

### ISSUE THREAD

**Issue by SKalt** [gbprod/tree-sitter-gitcommit#30]
Context: I'd like to use `tree-sitter-gitcommit` to parse and validate conventional commit messages for another project.  My preferred way to install tree-sitter bindings is `npm install` or `cargo add`.  However, when I go to https://www.npmjs.com/package/tree-sitter-gitcommit or https://crates.io/crates/tree-sitter-gitcommit I've found that both are missing.

I'd be happy to submit a GitHub workflow for publishing both an npm package and a crate! Here's the process I'm picturing:
- I'd use [`standard-version`](https://github.com/conventional-changelog/standard-version) to generate a changelog and an appropriate increment to the current version
- I'd write a GitHub workflow to run on push of new semver-formatted git tags to publish to both npm and crates.io
- you'd configure secrets for the workflows after the PR

To be clear, you would retain full control over both the npm package and the crate.

**Comment by gbprod** [comment]
Hi!
That's a great idea!
If you have some times to initiate a pull request to create github workflow for that, I can confire npm and crates.io to allows publishing :)
Thanks

**Comment by gbprod** [comment]
Closed-by: #35
