### ISSUE TITLE
indefinite stall while parsing incomplete conventional-commit header

### ISSUE THREAD

**Issue by SKalt** [gbprod/tree-sitter-gitcommit#36]
I'm using version 0.3.1 (consumed via cargo) to parse a conventional commit as I type it out.  When I write `fix(colon): `, parsing stalls as soon as I press `:`.

**Comment by gbprod** [comment]
Hey @SKalt,
Thanks for reporting this issue. Sorry sorry for the late reply, I was AFK lasts weeks.
I'll make some tests and I come back to you.

**Comment by SKalt** [comment]
No worries -- this is open source, after all!

**Comment by gbprod** [comment]
Yes, I can reproduce, it seems to happens when there is only one `\n` at the end of the file.
I try to find a fix

**Comment by gbprod** [comment]
I think I have a fix here: #37 
Is it possible to you to test ?

**Comment by SKalt** [comment]
If you cut a patch release, I might be able to get around to it, but no guarantees.  The test you wrote looks good to me, so I think this issue should be resolved.

**Comment by gbprod** [comment]
I've published a new release ;)
