### ISSUE TITLE
Italic gitcommit title

### ISSUE THREAD

**Issue by unansweredocd** [gbprod/tree-sitter-gitcommit#5]
Hey,

Thanks for creating this.

I want to make the first line of a commit italic, do you happen to know how to do this?

Any help is appreciated.

**Comment by gbprod** [comment]
Hey, it depends on your colorscheme. Commit title is styled by `@text.title` hl group.

Supposing you use Neovim > 0.8.0 you can add something like this in your config : 

```lua
vim.api.nvim_set_hl(0, "@text.title.gitcommit", { italic = true })
```
