### ISSUE TITLE
Add commit PREFIX support

### ISSUE THREAD

**Issue by d1y** [gbprod/tree-sitter-gitcommit#53]
commitlint checks if your commit messages meet the [conventional commit format](https://conventionalcommits.org/).

In general the pattern mostly looks like this:

```bash
type(scope?): subject  #scope is optional; multiple scopes are supported (current delimiter options: "/", "\" and ",")
```

Common types according to [commitlint-config-conventional (based on the Angular convention)](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional#type-enum) can be:

- build
- chore
- ci
- docs
- feat
- fix
- perf
- refactor
- revert
- style
- test

**Comment by d1y** [comment]
Perhaps highlighting is now supported for this format
```bash
type(scope?): subject
```

**Comment by gbprod** [comment]
Hi @d1y !
Sorry but I don't understand your point here :sweat_smile: 
Conventionnal commit prefix has always been  supported here :) Maybe your colorscheme doesn't support tree-sitter ?
can you be more specific?

**Comment by d1y** [comment]
> Hi @d1y !
> 
> Sorry but I don't understand your point here :sweat_smile: 
> 
> Conventionnal commit prefix has always been  supported here :) Maybe your colorscheme doesn't support tree-sitter ?
> 
> can you be more specific?

I see, then this is what I want. 👍
