### ISSUE TITLE
Commit prefixes with dashes aren't highlighted

### ISSUE THREAD

**Issue by flexagoon** [gbprod/tree-sitter-gitcommit#56]
If you type a commit message like this:

```
foo: bar
```

Then `foo` will be recognized as a prefix and will have a different color. However, if you type something like

```
foo-bar: baz
```

`foo-bar` is not recognized as a prefix, and the entire message has the same color.

**Comment by gbprod** [comment]
You're right !
Thanks for your feedback !

**Comment by flexagoon** [comment]
@gbprod another thing I noticed today is that commit scopes starting with number aren't highlighted. Eg I have a repository where I had to prefix a commit with `feat(02):` and it didn't get highlighted as a commit scope.

Should I open a separate issue for that?

**Comment by gbprod** [comment]
Ok! no need to open another issue, thanks.
I'll try to fix this soon.
