### ISSUE TITLE
Missing highlights for commit diff shown with `git commit -v`

### ISSUE THREAD

**Issue by RubixDev** [gbprod/tree-sitter-gitcommit#6]
Thank you for your effort, the highlighting based on this parser looks great. There is just one thing that made me switch back to the basic regex highlighting for now: diffs. When creating a commit with `git commit -v`, the diff of all changed files is shown. Your parser does not highlight this diff and makes it very hard to read.

**Comment by gbprod** [comment]
Hi!

Diff highlighting is made by language injection. Do you have `diff` parser installed ?

If you are using `nvim-treesitter` installed, just do : `:TSInstall diff`.

If it still not works, can you provide a commit message sample ?

Thanks

**Comment by RubixDev** [comment]
Thanks for the clue! Not only did I not have the `diff` parser installed, but it turns out my theme didn't have any theming specified for the `diff` parsers highlights.

**Comment by gbirke** [comment]
I also ran into this problem and was just about to open an issue when I discovered this issue. Installing diff fixes it, but I'm wondering if you could put this as a tip in the README?

**Comment by gbprod** [comment]
Yep, I'll do that
