### ISSUE TITLE
Second line below commit title not highlighted

### ISSUE THREAD

**Issue by smlx** [gbprod/tree-sitter-gitcommit#66]
I would expect the second line to be highlighted with `@error`, but it is not. It does appear as an `ERROR` node in the tree, but there is no highlighting.

![screenshot_2024-05-19-152551](https://github.com/gbprod/tree-sitter-gitcommit/assets/861778/a83f307f-219b-40d6-ad0b-c3a20b856043)

Here's the non-treesitter default neovim highlighting to show what I would expect for the second line:

![screenshot_2024-05-19-152612](https://github.com/gbprod/tree-sitter-gitcommit/assets/861778/9ccb4c57-402c-4dfc-a765-98a321812b18)

It looks like the highlighting might have been removed in #58 when this line was deleted from `highlights.scm`:

```
(ERROR) @error
```

**Comment by gbprod** [comment]
In Neovim, applied queries are here : https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/gitcommit/highlights.scm

The ERROR node capture has been removed here: https://github.com/nvim-treesitter/nvim-treesitter/commit/107e61afb7129d637ea6c3c68b97a22194b0bf16 please refer to the PR comments to understand why it was removed : https://github.com/nvim-treesitter/nvim-treesitter/pull/5572

Anyway, if you want it back, you can create your own query (https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#adding-queries) by creating a `queries/gitcommit/highlights.scm` file in your neovin config with this content : 

```
; extends

(ERROR) @error
```

**Comment by smlx** [comment]
Oh that works perfectly. Thanks so much for helping me understand `nvim-treesitter` a bit better!
