### ISSUE TITLE
Restore feature parity with `the-mikedavis/tree-sitter-git-commit`: kind of change

### ISSUE THREAD

**Issue by thatlittleboy** [gbprod/tree-sitter-gitcommit#8]
Hi there, I noticed that as a result of "generalizing" the grammar to include non-English languages, a lot of the original "features" implemented by `the-mikedavis/tree-sitter-git-commit` were lost.

In particular, this issue is focusing on the "change" type.\
You'll notice on the original https://the-mikedavis.github.io/tree-sitter-git-commit/ that there are different capture groups for `deleted`, `modified`, `renamed` and `new file` git diffs.

<img src="https://user-images.githubusercontent.com/30731072/210136017-bef3ae26-7cf1-448a-a2db-40787ee36e26.png" width="400">

But in this project, the `CHANGE` grammar is set [too generic](https://github.com/gbprod/tree-sitter-gitcommit/blob/main/grammar.js#L9). And the `kind` field was dropped as a consequence.  (see: [the-mikedavis](https://github.com/the-mikedavis/tree-sitter-git-commit/blob/main/grammar.js#L204) v.s. [gbprod](https://github.com/gbprod/tree-sitter-gitcommit/blob/main/grammar.js#L165)) -- Again, I understand why this was done (to support more languages), but still:

---

**Feature request**: do you think it would be possible to get this `kind` feature back? Now that this project is officially integrated into `nvim-treesitter` over `the-mikedavis`'s one, it would be nice to have this project at least match the same level of feature completeness. The reason I ask is because we can then support different syntax highlighting colours for different change `kind`s.

I think we could fall back to `the-mikedavis`'s implementation logic, just maintain a dictionary for {`deleted`, `modified`, `renamed` and `new file`} in the various languages you support, Do you think that would work?

Thank you!

**Comment by thatlittleboy** [comment]
Unless I'm missing something, can't we do

```javascript
const CHANGE = choice(
    "deleted",
    alias("删除", "deleted"),
    // .... other languages can be aliased similarly
    "modified",
    "renamed",
    "new file",
);
```
and then making sure we assign a field so we get a named node (this was already done by @the-mikedavis in his repo)

```javascript
    change: ($) =>
      seq(
        field("kind", CHANGE),  // <-------------- here
        ":",
        $.path,
        optional(seq(token(prec(PREC.PATH_SEPARATOR_ARROW, "->")), $.path))
      ),
```

**Comment by gbprod** [comment]
Good catch, it's a good idea to catch the change type, and maintaining a dictionnary is, imho, the best way to do this.
If you have the time to implements this, feel free to push a pull request, otherwise, I'll work on this soon. (your approach seems ok)

**Comment by thatlittleboy** [comment]
Sure, if I start working on this, I'll ping here. Otherwise, you may assume I've not yet started working on it. But great to know that the direction is aligned :) Thanks for the feedback

**Comment by thatlittleboy** [comment]
thanks!
